# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cuenta Ahorro', 'Cuenta Ahorro'), ('Cuenta Corriente', 'Cuenta Corriente')], max_length=16)),
                ('pin', models.CharField(max_length=4)),
                ('num_acc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DecimalField(decimal_places=2, max_digits=30)),
                ('deferrer', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('lock', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cod', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('num_check', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ident', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Formato de cédula inválido.', regex='^[VEJ]{1}-\\d{6,9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_installments', models.IntegerField()),
                ('paid_installments', models.IntegerField()),
                ('overdue_installments', models.IntegerField()),
                ('starting_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('details', models.CharField(blank=True, max_length=128)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payments_Tdc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Payments_Tlf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('CANTV', 'CANTV'), ('DIGITEL', 'DIGITEL'), ('MOVILNET', 'MOVILNET'), ('MOVISTAR', 'MOVISTAR')], max_length=10)),
                ('num_tlf', models.CharField(max_length=11)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Account')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Movement')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_card', models.CharField(max_length=20, unique=True)),
                ('month', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=2)),
                ('ccv', models.CharField(max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Tdc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MASTERCARD'), ('AMERICAN EXPRESS', 'AMERICAN EXPRESS')], max_length=16)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=30)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=30)),
                ('status', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Deposito', 'Depósito'), ('Retiro', 'Retiro'), ('POS', 'POS')], max_length=10)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.Account')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Movement')),
                ('tdc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.Tdc')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Pagos', 'Pagos'), ('Transferencia', 'Transferencia')], max_length=13)),
                ('acc_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_dest', to='api_app.Account')),
                ('acc_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_source', to='api_app.Account')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Movement')),
            ],
        ),
        migrations.AddField(
            model_name='payments_tdc',
            name='card_dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Tdc'),
        ),
        migrations.AddField(
            model_name='payments_tdc',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Movement'),
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together=set([('name', 'cod')]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Branch'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Customer'),
        ),
        migrations.AddField(
            model_name='account',
            name='balances',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Balance'),
        ),
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Branch'),
        ),
        migrations.AddField(
            model_name='account',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Product'),
        ),
    ]
